### ISSUE TITLE
zoneinfo._common.ZoneInfoNotFoundError: 'No time zone found with key Asia/Beijing'

### ISSUE THREAD

**Issue by EchoShoot** [scrapinghub/dateparser#1168]
Asia/Beijing is UnknownTimeZone, but Asia/Shanghai is OK

```
Traceback (most recent call last):
  File "/home/echoshoot/Desktop/WeiboSearch/spider.py", line 5, in <module>
    spider.start(task_id='7065543812')
  File "/home/echoshoot/Desktop/WeiboSearch/WeiboSpider/spiders.py", line 70, in start
    datas = self.parse_horizontal(task, token)  # 获取下一页
  File "/home/echoshoot/Desktop/WeiboSearch/WeiboSpider/spiders.py", line 40, in parse_horizontal
    items = fetcher.post.parse(resp)
  File "/home/echoshoot/Desktop/WeiboSearch/WeiboSpider/fetcher/post.py", line 88, in parse
    "publish_date": dateparser.parse(data['created_at']),
  File "/opt/anaconda3/envs/WeiboSearch/lib/python3.10/site-packages/dateparser/conf.py", line 93, in wrapper
    return f(*args, **kwargs)
  File "/opt/anaconda3/envs/WeiboSearch/lib/python3.10/site-packages/dateparser/__init__.py", line 61, in parse
    data = parser.get_date_data(date_string, date_formats)
  File "/opt/anaconda3/envs/WeiboSearch/lib/python3.10/site-packages/dateparser/date.py", line 451, in get_date_data
    parsed_date = _DateLocaleParser.parse(
  File "/opt/anaconda3/envs/WeiboSearch/lib/python3.10/site-packages/dateparser/date.py", line 200, in parse
    return instance._parse()
  File "/opt/anaconda3/envs/WeiboSearch/lib/python3.10/site-packages/dateparser/date.py", line 204, in _parse
    date_data = self._parsers[parser_name]()
  File "/opt/anaconda3/envs/WeiboSearch/lib/python3.10/site-packages/dateparser/date.py", line 224, in _try_freshness_parser
    return freshness_date_parser.get_date_data(self._get_translated_date(), self._settings)
  File "/opt/anaconda3/envs/WeiboSearch/lib/python3.10/site-packages/dateparser/freshness_date_parser.py", line 156, in get_date_data
    date, period = self.parse(date_string, settings)
  File "/opt/anaconda3/envs/WeiboSearch/lib/python3.10/site-packages/dateparser/freshness_date_parser.py", line 93, in parse
    now = datetime.now(self.get_local_tz())
  File "/opt/anaconda3/envs/WeiboSearch/lib/python3.10/site-packages/dateparser/freshness_date_parser.py", line 41, in get_local_tz
    return get_localzone()
  File "/opt/anaconda3/envs/WeiboSearch/lib/python3.10/site-packages/tzlocal/unix.py", line 209, in get_localzone
    _cache_tz = _get_localzone()
  File "/opt/anaconda3/envs/WeiboSearch/lib/python3.10/site-packages/tzlocal/unix.py", line 186, in _get_localzone
    tz = pds.timezone(tzname)
  File "/opt/anaconda3/envs/WeiboSearch/lib/python3.10/site-packages/pytz_deprecation_shim/_impl.py", line 41, in timezone
    raise get_exception(UnknownTimeZoneError, key)
pytz_deprecation_shim._exceptions._make_pytz_derived_errors.<locals>.UnknownTimeZoneError: 'Asia/Beijing'
```

**Comment by EchoShoot** [comment]
use this time to test:  `Mon Mar 27 12:26:18 +0800 2023`

**Comment by EchoShoot** [comment]
这个问题是计算机本地时区设置的问题，把时区从 Asia/Beijing 改成 Asia/Shanghai 就能解决。
