### ISSUE TITLE
Cannot install package due requirements installation failure on jdatetime

### ISSUE THREAD

**Issue by MichalMazurek** [scrapinghub/dateparser#149]
Hi Guys,

This is what I get:

```
(test_env)➜  tests pip install git+https://github.com/scrapinghub/dateparser.git
Collecting git+https://github.com/scrapinghub/dateparser.git
  Cloning https://github.com/scrapinghub/dateparser.git to /var/folders/nn/zb9nw9296kq2jtk0_m86hbtc0000gn/T/pip-evb5ik6q-build
Collecting python-dateutil>=2.3 (from dateparser==0.3.2)
  Using cached python_dateutil-2.4.2-py2.py3-none-any.whl
Collecting PyYAML (from dateparser==0.3.2)
Collecting jdatetime (from dateparser==0.3.2)
  Using cached jdatetime-1.7.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/nn/zb9nw9296kq2jtk0_m86hbtc0000gn/T/pip-build-ts5yt6q1/jdatetime/setup.py", line 12, in <module>
        long_description=open('README.rst').read()
    FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'

    ----------------------------------------
Command "python setup.py egg_info" failed with err
```

After doing install of python-jalali, it works alright, so first I had to do:
 `pip install git+https://github.com/slashmili/python-jalali.git`

and then `pip install git+https://github.com/scrapinghub/dateparser.git`

**Comment by asadurski** [comment]
Thank you for reporting this. The authors of `jdatetime` library have already corrected that installation problem on their side. Please try again.

**Comment by MichalMazurek** [comment]
Thanks!
