### ISSUE TITLE
UnboundLocalError: local variable `prev_token` referenced before assignment

### ISSUE THREAD

**Issue by cedric-cordenier** [scrapinghub/dateparser#219]
The following string: "8 enero 2013 martes 7:03 AM EST 8 enero 2013 martes 7:03 AM EST"
seems to throw an UnboundLocalError exception when we try to parse it:

```
>>> dateparser.parse("8 enero 2013 martes 7:03 AM EST 8 enero 2013 martes 7:03 AM EST")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/dateparser/conf.py", line 81, in wrapper
    return f(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/dateparser/__init__.py", line 40, in parse
    data = parser.get_date_data(date_string, date_formats)
  File "/Library/Python/2.7/site-packages/dateparser/date.py", line 361, in get_date_data
    language, date_string, date_formats, settings=self._settings)
  File "/Library/Python/2.7/site-packages/dateparser/date.py", line 165, in parse
    return instance._parse()
  File "/Library/Python/2.7/site-packages/dateparser/date.py", line 175, in _parse
    date_obj = parser()
  File "/Library/Python/2.7/site-packages/dateparser/date.py", line 196, in _try_parser
    self._get_translated_date(), settings=self._settings)
  File "/Library/Python/2.7/site-packages/dateparser/conf.py", line 81, in wrapper
    return f(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/dateparser/date_parser.py", line 24, in parse
    date_obj, period = parse(date_string, settings=settings)
  File "/Library/Python/2.7/site-packages/dateparser/parser.py", line 81, in parse
    raise exceptions.pop(-1)
UnboundLocalError: local variable 'prev_token' referenced before assignment
```

**Comment by waqasshabbir** [comment]
thank you @cedric-cordenier, fixed in #227
