### ISSUE TITLE
ValueError: unknown locale: UTF-8

### ISSUE THREAD

**Issue by busla** [scrapinghub/dateparser#237]
I get this error on import:

```
Traceback (most recent call last):
  File "observer.py", line 1, in <module>
    import dateparser
  File "/Users/levy/Code/streampimp/venv/lib/python3.5/site-packages/dateparser/__init__.py", line 4, in <module>
    from .date import DateDataParser
  File "/Users/levy/Code/streampimp/venv/lib/python3.5/site-packages/dateparser/date.py", line 8, in <module>
    import regex as re
  File "/Users/levy/Code/streampimp/venv/lib/python3.5/site-packages/regex.py", line 683, in <module>
    _pattern_type = type(_compile("", 0, {}))
  File "/Users/levy/Code/streampimp/venv/lib/python3.5/site-packages/regex.py", line 436, in _compile
    pattern_locale = _getlocale()[1]
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/locale.py", line 577, in getlocale
    return _parse_localename(localename)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/locale.py", line 486, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8
```

My locale is set correctly:

```
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

The **international** setting in terminal is also set to UTF-8.

**Comment by ammar-azif** [comment]
Hello @busla , it looks like your LC_CTYPE locale is not recognized as valid value. Here's my locale (mac os x)

```
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```

Try prepending language locale (en_US., en_GB. etc to "UTF-8").

Add these example lines to your ~/.bash_profile

```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```

**Comment by waqasshabbir** [comment]
@busla did Ammar's suggestion fixed the problem for you?

**Comment by rooterkyberian** [comment]
doesn't seem like `dateparser` problem, but `regex` and they also decided it was a configuration issue:
https://bitbucket.org/mrabarnett/mrab-regex/issues/234/cant-import-regex-on-python-361-valueerror

**Comment by busla** [comment]
Apologies for not replying back to this thread, I somehow completely missed the replies.

Let me look into how I resolved this and report back.

Thanks for contributing and for the support.

**Comment by asadurski** [comment]
Closing the issue. Please open it if the problem reappears.
