### ISSUE TITLE
TypeError: Error when calling the metaclass bases

### ISSUE THREAD

**Issue by geca** [scrapinghub/dateparser#246]
All requirements installed. I get the following error when importing dateparser.

```
Python 2.7 (r27:82525, Jul  4 2010, 09:01:59) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import dateparser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\dateparser\__init__.py", line 4, in <module>
    from .date import DateDataParser
  File "C:\Python27\lib\site-packages\dateparser\date.py", line 11, in <module>
    from dateparser.date_parser import date_parser
  File "C:\Python27\lib\site-packages\dateparser\date_parser.py", line 10, in <module>
    from .conf import apply_settings
  File "C:\Python27\lib\site-packages\dateparser\conf.py", line 7, in <module>
    from ruamel.yaml import load as load_yaml
  File "C:\Python27\lib\site-packages\ruamel\yaml\__init__.py", line 81, in <module>
    from ruamel.yaml.main import *  # NOQA
  File "C:\Python27\lib\site-packages\ruamel\yaml\main.py", line 6, in <module>
    from typing import List, Set, Dict, Tuple, Optional, Union, BinaryIO, IO, Any  # NOQA
  File "C:\Python27\lib\site-packages\typing.py", line 1536, in <module>
    class Type(type, Generic[CT]):
  File "C:\Python27\lib\site-packages\typing.py", line 926, in __new__
    self = super(GenericMeta, cls).__new__(cls, name, bases, namespace)
  File "C:\Python27\lib\site-packages\typing.py", line 95, in __new__
    return super(TypingMeta, cls).__new__(cls, str(name), bases, namespace)
  File "C:\Python27\lib\abc.py", line 92, in __new__
    for name in getattr(base, "__abstractmethods__", set()):
TypeError: Error when calling the metaclass bases
    'getset_descriptor' object is not iterable
>>>
```

**Comment by asadurski** [comment]
Unfortunately this seems to be an issue with your Python 2.7.0 and abstract classes. Can you upgrade to any more recent version? It should work with 2.7.2 and up.

**Comment by geca** [comment]
Upgraded to 2.7.12, works like a charm. Thanks.
