### ISSUE TITLE
ruamel.yaml v0.14 and greater causes an import error. Using earlier versions work.

### ISSUE THREAD

**Issue by FlipperPA** [scrapinghub/dateparser#297]
I've issued a PR to install `ruamel.yaml<0.14`, which fixes the import error. Here's the trace of the error I got with v0.14.2:

```
Python 3.5.3 (default, Feb 15 2017, 10:22:31)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dateparser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/blah1/blah2/virtualenvs/wrds-classroom-dev/lib/python3.5/site-packages/dateparser/__init__.py", line 4, in <module>
    from .date import DateDataParser
  File "/blah1/blah2/virtualenvs/wrds-classroom-dev/lib/python3.5/site-packages/dateparser/date.py", line 11, in <module>
    from dateparser.date_parser import date_parser
  File "/blah1/blah2/virtualenvs/wrds-classroom-dev/lib/python3.5/site-packages/dateparser/date_parser.py", line 9, in <module>
    from .utils import strip_braces, apply_timezone, localize_timezone
  File "/blah1/blah2/virtualenvs/wrds-classroom-dev/lib/python3.5/site-packages/dateparser/utils/__init__.py", line 8, in <module>
    import ruamel.yaml as yaml
  File "/blah1/blah2/virtualenvs/wrds-classroom-dev/lib64/python3.5/site-packages/ruamel/yaml/__init__.py", line 65, in <module>
    from ruamel.yaml.main import *  # NOQA
  File "/blah1/blah2/virtualenvs/wrds-classroom-dev/lib64/python3.5/site-packages/ruamel/yaml/main.py", line 10, in <module>
    from ruamel.yaml.error import *                                # NOQA
  File "/blah1/blah2/virtualenvs/wrds-classroom-dev/lib64/python3.5/site-packages/ruamel/yaml/error.py", line 9, in <module>
    from ruamel.yaml.compat import utf8
  File "/blah1/blah2/virtualenvs/wrds-classroom-dev/lib64/python3.5/site-packages/ruamel/yaml/compat.py", line 12, in <module>
    from typing import Any, Dict, Optional, List, Union, BinaryIO, IO, Text, Tuple   # NOQA
ImportError: cannot import name 'Text'
>>>
```

**Comment by asadurski** [comment]
ruamel.yaml removed from dependencies. Closing.
