### ISSUE TITLE
Parse ':r.' gives IndexError

### ISSUE THREAD

**Issue by merito** [scrapinghub/dateparser#328]
Hi,
trying to parse `:r.` running current master (here in pycharm) I've got this error
```
Traceback (most recent call last):
  File "/opt/pycharm-community-2017.1/helpers/pydev/pydevd.py", line 1578, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/opt/pycharm-community-2017.1/helpers/pydev/pydevd.py", line 1015, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/opt/pycharm-community-2017.1/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/merito/dateparser/main.py", line 5, in <module>
    dateparser.parse(':r.')
  File "/home/merito/dateparser/dateparser/conf.py", line 84, in wrapper
    return f(*args, **kwargs)
  File "/home/merito/dateparser/dateparser/__init__.py", line 40, in parse
    data = parser.get_date_data(date_string, date_formats)
  File "/home/merito/dateparser/dateparser/date.py", line 379, in get_date_data
    language, date_string, date_formats, settings=self._settings)
  File "/home/merito/dateparser/dateparser/date.py", line 176, in parse
    return instance._parse()
  File "/home/merito/dateparser/dateparser/date.py", line 186, in _parse
    date_obj = parser()
  File "/home/merito/dateparser/dateparser/date.py", line 207, in _try_parser
    self._get_translated_date(), settings=self._settings)
  File "/home/merito/dateparser/dateparser/conf.py", line 84, in wrapper
    return f(*args, **kwargs)
  File "/home/merito/dateparser/dateparser/date_parser.py", line 26, in parse
    date_obj, period = parse(date_string, settings=settings)
  File "/home/merito/dateparser/dateparser/parser.py", line 70, in parse
    raise exceptions.pop(-1)
  File "/home/merito/dateparser/dateparser/parser.py", line 64, in parse
    res = parser(datestring, settings)
  File "/home/merito/dateparser/dateparser/parser.py", line 156, in parse
    for token, _ in tokens.tokenize():
  File "/home/merito/dateparser/dateparser/parser.py", line 550, in tokenize
    type, _ = self._switch(token[-1], nextchar)
IndexError: string index out of range
```
I work on Debian testing with Python 3.5.3.

**Comment by issac-sayone** [comment]
Any solution?

**Comment by kishan3** [comment]
Since this is fixed can this be closed @ArturGaspar ?

**Comment by Gallaecio** [comment]
```
>>> dateparser.parse(':r.')
>>> dateparser.__version__
'0.7.2'
```
