### ISSUE TITLE
Library Dateparser Does Convert to Exe - Outputs error

### ISSUE THREAD

**Issue by kyeer** [scrapinghub/dateparser#349]
Dateparser runs great in PyCharm IDE and Command Line but when converted to exe it does outputs below error. Based on the error it looks like the issue stems from line 102 of Yaml library which I've copied below.

**Error Output**
```
Traceback (most recent call last):
  File "easyprocess\examples\Cassia.py", line 15, in <module>
  File "c:\users\kyeand~1\appdata\local\temp\pip-build-jiybvi\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "dateparser\__init__.py", line 4, in <module>
  File "c:\users\kyeand~1\appdata\local\temp\pip-build-jiybvi\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "dateparser\date.py", line 11, in <module>
  File "c:\users\kyeand~1\appdata\local\temp\pip-build-jiybvi\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "dateparser\date_parser.py", line 10, in <module>
  File "c:\users\kyeand~1\appdata\local\temp\pip-build-jiybvi\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "dateparser\conf.py", line 66, in <module>
  File "dateparser\conf.py", line 32, in __init__
  File "dateparser\conf.py", line 46, in _get_settings_from_yaml
  File "dateparser\utils\__init__.py", line 188, in __init__
  File "ruamel\yaml\loader.py", line 36, in __init__
  File "ruamel\yaml\scanner.py", line 83, in __init__
  File "ruamel\yaml\scanner.py", line 99, in reset_scanner
  File "ruamel\yaml\scanner.py", line 424, in fetch_stream_start
  File "ruamel\yaml\reader.py", line 159, in get_mark
  File "ruamel\yaml\reader.py", line 102, in stream
ruamel.yaml.error.YAMLStreamError: input stream needs to specified
```

**Ruamel\yaml\reader.py line 102**
```
@property
    def stream(self):
        # type: () -> Any
        try:
            return self._stream
        except AttributeError:
            raise YAMLStreamError('input stream needs to specified')
```

**Comment by asadurski** [comment]
@kyeer: Dateparser was not built with such conversions in mind, but could you try with version 0.7.0?
The error was probably caused by ruamel.yaml dependency and we dropped it in the recent release.

**Comment by Gallaecio** [comment]
Closing due to a lack of feedback.
