### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 100: invalid start byte

### ISSUE THREAD

**Issue by huvar** [scrapinghub/dateparser#353]
Hi,

I have this error when running my program in a raspberry pi. It should not happen because I am passing strings (not bytes) to the dateparser.parse method.
When running the same program on a different computer I do not have any issue. Any clue about what is happening?

Traceback:
Traceback (most recent call last):
    pub_date = dateparser.parse(pub_date)
  File "/home/xbian/.local/lib/python3.5/site-packages/dateparser/conf.py", line 84, in wrapper
    return f(*args, **kwargs)
  File "/home/xbian/.local/lib/python3.5/site-packages/dateparser/__init__.py", line 40, in parse
    data = parser.get_date_data(date_string, date_formats)
  File "/home/xbian/.local/lib/python3.5/site-packages/dateparser/date.py", line 371, in get_date_data
    language, date_string, date_formats, settings=self._settings)
  File "/home/xbian/.local/lib/python3.5/site-packages/dateparser/date.py", line 168, in parse
    return instance._parse()
  File "/home/xbian/.local/lib/python3.5/site-packages/dateparser/date.py", line 178, in _parse
    date_obj = parser()
  File "/home/xbian/.local/lib/python3.5/site-packages/dateparser/date.py", line 191, in _try_freshness_parser
    return freshness_date_parser.get_date_data(self._get_translated_date(), self._settings)
  File "/home/xbian/.local/lib/python3.5/site-packages/dateparser/freshness_date_parser.py", line 147, in get_date_data
    date, period = self.parse(date_string, settings)
  File "/home/xbian/.local/lib/python3.5/site-packages/dateparser/freshness_date_parser.py", line 94, in parse
    self.now = datetime.now(self.get_local_tz())
  File "/home/xbian/.local/lib/python3.5/site-packages/dateparser/freshness_date_parser.py", line 46, in get_local_tz
    return get_localzone()
  File "/home/xbian/.local/lib/python3.5/site-packages/tzlocal/unix.py", line 123, in get_localzone
    _cache_tz = _get_localzone()
  File "/home/xbian/.local/lib/python3.5/site-packages/tzlocal/unix.py", line 56, in _get_localzone
    etctz = data.strip().decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 100: invalid start byte

Working Configuration:
python3 --version
Python 3.5.2

pip3 list | grep dateparser
dateparser (0.6.0)

pip3 list | grep tzlocal
tzlocal (1.4)

RaspberryPI Info: 
python3 --version
Python 3.5.3

pip3 list | grep dateparser
dateparser (0.6.0)

pip3 list | grep tzlocal
tzlocal (1.4)

**Comment by cathalgarvey** [comment]
Hey @huvar - Could you provide an example date string that I could use to help diagnose? It looks to me, at a guess, like the `bytes.strip` method might be mangling the Unicode in the string so it can no longer `bytes.decode` to Unicode, but I'd need an example string to verify this - As far as I know this shouldn't happen unless the string ends on a unicode grapheme whose codepoints contain ASCII whitespace characters.
