### ISSUE TITLE
Tests Fail in Python3k

### ISSUE THREAD

**Issue by makefu** [scrapinghub/dateparser#364]
Hey, i wanted to test the latest version of dateparser in nix (a functional package manager) but it seems that currently tests fail in py3k:

```
======================================================================
FAIL: test_dates_not_supported_by_date_time_0_5000_years_ago (tests.test_freshness_date_parser.TestFreshnessDateDataParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/sfha3gph75ggkz5sgd74h98j150iyvpp-python3.6-nose-parameterized-0.5.0/lib/python3.6/site-packages/nose_parameterized/parameterized.py", line 365, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/build/dateparser/tests/test_freshness_date_parser.py", line 720, in test_dates_not_supported_by_date_time
    "('year must be in 1..9999'"])
  File "/build/dateparser/tests/__init__.py", line 26, in then_error_was_raised
    allowed_substrings, self.error))
AssertionError: False is not true : Didn't found any of the expected messages (['year is out of range', "('year must be in 1..9999'"]) -- message was: ValueError('year -2986 is out of range',)

======================================================================
FAIL: test_dates_not_supported_by_date_time_1_2014_years_ago (tests.test_freshness_date_parser.TestFreshnessDateDataParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/sfha3gph75ggkz5sgd74h98j150iyvpp-python3.6-nose-parameterized-0.5.0/lib/python3.6/site-packages/nose_parameterized/parameterized.py", line 365, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/build/dateparser/tests/test_freshness_date_parser.py", line 720, in test_dates_not_supported_by_date_time
    "('year must be in 1..9999'"])
  File "/build/dateparser/tests/__init__.py", line 26, in then_error_was_raised
    allowed_substrings, self.error))
AssertionError: False is not true : Didn't found any of the expected messages (['year is out of range', "('year must be in 1..9999'"]) -- message was: ValueError('year 0 is out of range',)

======================================================================
FAIL: test_dates_not_supported_by_date_time_2_24165_months_ago (tests.test_freshness_date_parser.TestFreshnessDateDataParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/sfha3gph75ggkz5sgd74h98j150iyvpp-python3.6-nose-parameterized-0.5.0/lib/python3.6/site-packages/nose_parameterized/parameterized.py", line 365, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/build/dateparser/tests/test_freshness_date_parser.py", line 720, in test_dates_not_supported_by_date_time
    "('year must be in 1..9999'"])
  File "/build/dateparser/tests/__init__.py", line 26, in then_error_was_raised
    allowed_substrings, self.error))
AssertionError: False is not true : Didn't found any of the expected messages (['year is out of range', "('year must be in 1..9999'"]) -- message was: ValueError('year 0 is out of range',)

----------------------------------------------------------------------
Ran 1522 tests in 78.636s

FAILED (failures=3, errors=1, skipped=7)
```

`convertdate` is missing (which resulted in the one error) - no problem on dateparser side, i just haven't packaged it yet. however the tests could be skipped if the tool is not available.

The tests run successfully in `python2`.

Cheers!

**Comment by nico202** [comment]
bump? Now the error is missing, but the failures exists.
It's just a matter of changing the expected error message right?

**Comment by dotlambda** [comment]
@makefu You can close this one. I just managed to enable checks on Python 3: https://github.com/NixOS/nixpkgs/pull/34768

**Comment by makefu** [comment]
@dotlambda great, thanks!
