### ISSUE TITLE
AttributeError: module 'dateparser' has no attribute 'parse'

### ISSUE THREAD

**Issue by fboender** [scrapinghub/dateparser#386]
I'm having a very strange problem with dateparser that I can't seem to figure out. After installing dateparser and trying to use it, I got:

    AttributeError: module 'dateparser' has no attribute 'parse'

Now this is very strange, because I installed it on a different machine with the exact same OS moments before, and it worked just fine there. I have a sneaking suspicion that this may be something unrelated to dateparser, but unfortunately all the other packages I'm using in the same manner are working just fine. I'm hoping someone here may be able to shed some light on this.

First, some info:

* Ubuntu 16.04.3 LTS
* Comes with Python 2.7.12 and Python 3.5.2
* I generally use virtualenvs, but in this case I'm not able to do so.

Here's how I installed dateparser:

    $ sudo pip3 install dateparser
    [sudo] password for fboender: 
    The directory '/home/fboender/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    The directory '/home/fboender/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    Collecting dateparser
      Downloading dateparser-0.7.0-py2.py3-none-any.whl (357kB)
        100% |████████████████████████████████| 358kB 1.8MB/s 
    Requirement already satisfied (use --upgrade to upgrade): pytz in /usr/local/lib/python3.5/dist-packages (from dateparser)
    Collecting regex (from dateparser)
      Downloading regex-2018.02.08.tar.gz (620kB)
        100% |████████████████████████████████| 624kB 1.0MB/s 
    Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /usr/local/lib/python3.5/dist-packages (from dateparser)
    Collecting tzlocal (from dateparser)
      Downloading tzlocal-1.5.1.tar.gz
    Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil->dateparser)
    Installing collected packages: regex, tzlocal, dateparser
      Running setup.py install for regex ... done
      Running setup.py install for tzlocal ... done
    Successfully installed dateparser-0.7.0 regex-2018.2.8 tzlocal-1.5.1
    You are using pip version 8.1.1, however version 9.0.1 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.

However, it does not seem to work:

    $ python3 -c "import dateparser; print(dateparser.parse)"
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    AttributeError: module 'dateparser' has no attribute 'parse'

The strange thing is, when I become root, it *does* work:

    $ sudo python3 -c "import dateparser; print(dateparser.parse)"
    [sudo] password for fboender: 
    <function parse at 0x7f6f71077a60>

For the life of me, I cannot explain this. I've tried a completely clean environment, even a completely new user. I've checked the PYTHONPATH and sys.path for weird things, but I can't find any difference:

    $ env - /bin/sh
    $ set | grep PYTHONPATH
    $ which python3
    /usr/bin/python3
    $ /usr/bin/python3 -c "import dateparser; print(dateparser.parse)"
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    AttributeError: module 'dateparser' has no attribute 'parse'
    $ sudo python3 -c "import sys; print(sys.path)"
    ['', '/usr/lib/python35.zip', '/usr/lib/python3.5', '/usr/lib/python3.5/plat-x86_64-linux-gnu', '/usr/lib/python3.5/lib-dynload', '/usr/local/lib/python3.5/dist-packages', '/usr/lib/python3/dist-packages']

And as root, nothing seems different:

    $ sudo su - 
    # env - /bin/sh
    # set | grep PYTHONPATH
    # which python3
    /usr/bin/python3
    # /usr/bin/python3 -c "import dateparser; print(dateparser.parse)"
    <function parse at 0x7f46beeaca60>
    # sudo /usr/bin/python3 -c "import sys; print(sys.path)"
    ['', '/usr/lib/python35.zip', '/usr/lib/python3.5', '/usr/lib/python3.5/plat-x86_64-linux-gnu', '/usr/lib/python3.5/lib-dynload', '/usr/local/lib/python3.5/dist-packages', '/usr/lib/python3/dist-packages']

I've tried:

* Uninstalling dateparser with pip v8.1.1, upgrading pip to the latest version and reinstalling dateparser.
* Removing all the .cache directories in the various home dirs of the involved users.
* Removing all the `__pycache__` directories in `dist-packages/dateparser*`
* Removing all the `*.pyc*` files in `dist-packages/dateparser*`

None of these seem to work. Installing it in a virtualenv *does* work, but I've got another package which won't install in a virtualenv for some reason.

I don't think I've ever had this exact problem before with any other packages. (not that I'm blaming dateparser here... like I said, it feels like something deeper is wrong).

Any ideas?

**Comment by fboender** [comment]
Found the solution. The permissions on the newly installed packages were incorrect:

    drwx--S---  8 root staff    4096 Feb 19 22:26 dateparser
    drwx--S---  2 root staff    4096 Feb 19 22:26 dateparser-0.7.0.dist-info
    drwx--S---  3 root staff    4096 Feb 19 22:26 dateparser_data
    drwxr-sr-x  5 root staff    4096 Feb 19 22:00 dateutil

If I fix them manually:

    # cd /usr/local/lib/python3.5/dist-packages 
    # find dateparser -type d -exec chmod 755 '{}' \;
    # find dateparser -type d -exec chmod 755 '{}' \;
    # find dateparser -type f -exec chmod 644 '{}' \;
    # find regex-2018.2.8.dist-info -type f -exec chmod 644 '{}' \;
    # find dateparser-0.7.0.dist-info -type f -exec chmod 644 '{}' \;
    # find dateparser_data -type f -exec chmod 644 '{}' \;
    # find dateparser-0.7.0.dist-info -type d -exec chmod 755 '{}' \;
    # find dateparser_data -type d -exec chmod 755 '{}' \;
    # find tzlocal -type d -exec chmod 755 '{}' \;
    $ find tzlocal-1.5.1.dist-info -type d -exec chmod 755 '{}' \;
    # find tzlocal -type f -exec chmod 644 '{}' \;
    
Now it works:

    $ python3 
    Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
    [GCC 5.4.0 20160609] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import dateparser

My hosting provider seems to set the umask for the root user to a different value than stock Ubuntu 16.04.

    root @ hostingprovider # umask
    0077
    root @ stockubuntu # umask
    0022

Not sure if this is an issue with dateparser or with pip. The `dateutil` package was installed half an hour earlier, and it didn't have this problem, so I'm thinking it might be something with dateparser.

regards,

Ferry

**Comment by fboender** [comment]
PS, if I set my umask correctly manually before installing, it works (I reverted to an earlier snapshot of the VPS just to get a clean working environment):

    # umask 022
    # pip3 install dateparser
    Collecting dateparser
      Using cached dateparser-0.7.0-py2.py3-none-any.whl
    Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /usr/local/lib/python3.5/dist-packages (from dateparser)
    Collecting tzlocal (from dateparser)
    Collecting regex (from dateparser)
    Requirement already satisfied (use --upgrade to upgrade): pytz in /usr/local/lib/python3.5/dist-packages (from dateparser)
    Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil->dateparser)
    Installing collected packages: tzlocal, regex, dateparser
    Successfully installed dateparser-0.7.0 regex-2018.2.8 tzlocal-1.5.1
    You are using pip version 8.1.1, however version 9.0.1 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
    
    $ /usr/bin/python3 -c "import dateparser; print(dateparser.parse)"
    <function parse at 0x7f8500fa1a60>
