### ISSUE TITLE
 'utf-8' codec can't decode byte 0xfa in position 1: invalid start byte

### ISSUE THREAD

**Issue by p0l4r** [scrapinghub/dateparser#405]
while trying to read a CSV file using pandas the following error occurred. please help - 

 b'Skipping line 3: expected 1 fields, saw 3\nSkipping line 7: expected 1 fields, saw 2\nSkipping line 8: expected 1 fields, saw 2\nSkipping line 9: expected 1 fields, saw 2\nSkipping line 13: expected 1 fields, saw 3\nSkipping line 14: expected 1 fields, saw 3\nSkipping line 17: expected 1 fields, saw 2\nSkipping line 19: expected 1 fields, saw 2\nSkipping line 20: expected 1 fields, saw 5\nSkipping line 22: expected 1 fields, saw 2\nSkipping line 25: expected 1 fields, saw 3\nSkipping line 26: expected 1 fields, saw 2\nSkipping line 27: expected 1 fields, saw 2\nSkipping line 29: expected 1 fields, saw 2\nSkipping line 31: expected 1 fields, saw 2\nSkipping line 42: expected 1 fields, saw 3\nSkipping line 52: expected 1 fields, saw 2\nSkipping line 57: expected 1 fields, saw 2\nSkipping line 61: expected 1 fields, saw 2\nSkipping line 65: expected 1 fields, saw 3\nSkipping line 69: expected 1 fields, saw 2\nSkipping line 70: expected 1 fields, saw 2\nSkipping line 71: expected 1 fields, saw 2\nSkipping line 79: expected 1 fields, saw 2\nSkipping line 85: expected 1 fields, saw 2\nSkipping line 86: expected 1 fields, saw 4\nSkipping line 88: expected 1 fields, saw 2\n'
Traceback (most recent call last):
  File "pandas\_libs\parsers.pyx", line 1175, in pandas._libs.parsers.TextReader._convert_tokens
  File "pandas\_libs\parsers.pyx", line 1281, in pandas._libs.parsers.TextReader._convert_with_dtype
  File "pandas\_libs\parsers.pyx", line 1297, in pandas._libs.parsers.TextReader._string_convert
  File "pandas\_libs\parsers.pyx", line 1539, in pandas._libs.parsers._string_box_utf8
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Toxic Comment Classification Bangla\Toxic Comment Classification - Copy.py", line 40, in <module>
    df = pd.read_csv('BanglaHate.csv',encoding='utf-8',error_bad_lines=False)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\io\parsers.py", line 709, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\io\parsers.py", line 455, in _read
    data = parser.read(nrows)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\io\parsers.py", line 1069, in read
    ret = self._engine.read(nrows)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\io\parsers.py", line 1839, in read
    data = self._reader.read(nrows)
  File "pandas\_libs\parsers.pyx", line 902, in pandas._libs.parsers.TextReader.read
  File "pandas\_libs\parsers.pyx", line 924, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas\_libs\parsers.pyx", line 1001, in pandas._libs.parsers.TextReader._read_rows
  File "pandas\_libs\parsers.pyx", line 1130, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas\_libs\parsers.pyx", line 1182, in pandas._libs.parsers.TextReader._convert_tokens
  File "pandas\_libs\parsers.pyx", line 1281, in pandas._libs.parsers.TextReader._convert_with_dtype
  File "pandas\_libs\parsers.pyx", line 1297, in pandas._libs.parsers.TextReader._string_convert
  File "pandas\_libs\parsers.pyx", line 1539, in pandas._libs.parsers._string_box_utf8
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 0: invalid start byte
>>> 
b'Skipping line 3: expected 1 fields, saw 3\nSkipping line 7: expected 1 fields, saw 2\nSkipping line 8: expected 1 fields, saw 2\nSkipping line 9: expected 1 fields, saw 2\nSkipping line 13: expected 1 fields, saw 3\nSkipping line 14: expected 1 fields, saw 3\nSkipping line 17: expected 1 fields, saw 2\nSkipping line 19: expected 1 fields, saw 2\nSkipping line 20: expected 1 fields, saw 5\nSkipping line 22: expected 1 fields, saw 2\nSkipping line 25: expected 1 fields, saw 3\nSkipping line 26: expected 1 fields, saw 2\nSkipping line 27: expected 1 fields, saw 2\nSkipping line 29: expected 1 fields, saw 2\nSkipping line 31: expected 1 fields, saw 2\nSkipping line 42: expected 1 fields, saw 3\nSkipping line 52: expected 1 fields, saw 2\nSkipping line 57: expected 1 fields, saw 2\nSkipping line 61: expected 1 fields, saw 2\nSkipping line 65: expected 1 fields, saw 3\nSkipping line 69: expected 1 fields, saw 2\nSkipping line 70: expected 1 fields, saw 2\nSkipping line 71: expected 1 fields, saw 2\nSkipping line 79: expected 1 fields, saw 2\nSkipping line 85: expected 1 fields, saw 2\nSkipping line 86: expected 1 fields, saw 4\nSkipping line 88: expected 1 fields, saw 2\n'
Traceback (most recent call last):
  File "pandas\_libs\parsers.pyx", line 1175, in pandas._libs.parsers.TextReader._convert_tokens
  File "pandas\_libs\parsers.pyx", line 1281, in pandas._libs.parsers.TextReader._convert_with_dtype
  File "pandas\_libs\parsers.pyx", line 1297, in pandas._libs.parsers.TextReader._string_convert
  File "pandas\_libs\parsers.pyx", line 1539, in pandas._libs.parsers._string_box_utf8
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Toxic Comment Classification Bangla\Toxic Comment Classification - Copy.py", line 40, in <module>
    df = pd.read_csv('BanglaHate.csv',encoding='utf-8',error_bad_lines=False)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\io\parsers.py", line 709, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\io\parsers.py", line 455, in _read
    data = parser.read(nrows)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\io\parsers.py", line 1069, in read
    ret = self._engine.read(nrows)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\io\parsers.py", line 1839, in read
    data = self._reader.read(nrows)
  File "pandas\_libs\parsers.pyx", line 902, in pandas._libs.parsers.TextReader.read
  File "pandas\_libs\parsers.pyx", line 924, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas\_libs\parsers.pyx", line 1001, in pandas._libs.parsers.TextReader._read_rows
  File "pandas\_libs\parsers.pyx", line 1130, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas\_libs\parsers.pyx", line 1182, in pandas._libs.parsers.TextReader._convert_tokens
  File "pandas\_libs\parsers.pyx", line 1281, in pandas._libs.parsers.TextReader._convert_with_dtype
  File "pandas\_libs\parsers.pyx", line 1297, in pandas._libs.parsers.TextReader._string_convert
  File "pandas\_libs\parsers.pyx", line 1539, in pandas._libs.parsers._string_box_utf8
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 0: invalid start byte

**Comment by wRAR** [comment]
Doesn't look related to dateparser.
