### ISSUE TITLE
dateparser.parse thorws IndexError for ':' 

### ISSUE THREAD

**Issue by undercutspiky** [scrapinghub/dateparser#444]
dateparser.parse(':') throws following error:
`
Traceback (most recent call last): File "<stdin>", line 1, in <module> File "C:\Users\D071834\anaconda3\envs\tensorflow-gpu\lib\site-packages\dateparser\conf.py", line 84, in wrapper return f(*args, **kwargs) File "C:\Users\D071834\anaconda3\envs\tensorflow-gpu\lib\site-packages\dateparser\__init__.py", line 40, in parse data = parser.get_date_data(date_string, date_formats) File "C:\Users\D071834\anaconda3\envs\tensorflow-gpu\lib\site-packages\dateparser\date.py", line 371, in get_date_data language, date_string, date_formats, settings=self._settings) File "C:\Users\D071834\anaconda3\envs\tensorflow-gpu\lib\site-packages\dateparser\date.py", line 168, in parse return instance._parse() File "C:\Users\D071834\anaconda3\envs\tensorflow-gpu\lib\site-packages\dateparser\date.py", line 178, in _parse date_obj = parser() File "C:\Users\D071834\anaconda3\envs\tensorflow-gpu\lib\site-packages\dateparser\date.py", line 199, in _try_parser self._get_translated_date(), settings=self._settings) File "C:\Users\D071834\anaconda3\envs\tensorflow-gpu\lib\site-packages\dateparser\conf.py", line 84, in wrapper return f(*args, **kwargs) File "C:\Users\D071834\anaconda3\envs\tensorflow-gpu\lib\site-packages\dateparser\date_parser.py", line 26, in parse date_obj, period = parse(date_string, settings=settings) File "C:\Users\D071834\anaconda3\envs\tensorflow-gpu\lib\site-packages\dateparser\parser.py", line 84, in parse raise exceptions.pop(-1) File "C:\Users\D071834\anaconda3\envs\tensorflow-gpu\lib\site-packages\dateparser\parser.py", line 78, in parse res = parser(datestring, settings) File "C:\Users\D071834\anaconda3\envs\tensorflow-gpu\lib\site-packages\dateparser\parser.py", line 170, in parse for token, _ in tokens.tokenize(): File "C:\Users\D071834\anaconda3\envs\tensorflow-gpu\lib\site-packages\dateparser\parser.py", line 566, in tokenize type, _ = self._switch(token[-1], nextchar) IndexError: string index out of range
`
It's same for similar strings like '#:', '####:', ':::' etc.

**Comment by wRAR** [comment]
It's because [`dateparser.parser._no_spaces_parser.parse`](https://github.com/scrapinghub/dateparser/blob/v0.7.0/dateparser/parser.py#L148) makes an empty string out of `:`. A simple check seems enough to fix this.
