### ISSUE TITLE
pytz.exceptions.UnknownTimeZoneError: ''

### ISSUE THREAD

**Issue by DrKendall** [scrapinghub/dateparser#462]
I am getting this error, well, actually no error context.
```
[root@vps584408 ~]# python3.6
Python 3.6.5 (default, Apr 10 2018, 17:08:37)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> import dateparser
>>> dateparser.parse("November 5 3:30 PM")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/dateparser/conf.py", line 81, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/dateparser/__init__.py", line 53, in parse
    data = parser.get_date_data(date_string, date_formats)
  File "/usr/lib/python3.6/site-packages/dateparser/date.py", line 404, in get_date_data
    locale, date_string, date_formats, settings=self._settings)
  File "/usr/lib/python3.6/site-packages/dateparser/date.py", line 177, in parse
    return instance._parse()
  File "/usr/lib/python3.6/site-packages/dateparser/date.py", line 187, in _parse
    date_obj = parser()
  File "/usr/lib/python3.6/site-packages/dateparser/date.py", line 200, in _try_freshness_parser
    return freshness_date_parser.get_date_data(self._get_translated_date(), self._settings)
  File "/usr/lib/python3.6/site-packages/dateparser/freshness_date_parser.py", line 147, in get_date_data
    date, period = self.parse(date_string, settings)
  File "/usr/lib/python3.6/site-packages/dateparser/freshness_date_parser.py", line 94, in parse
    self.now = datetime.now(self.get_local_tz())
  File "/usr/lib/python3.6/site-packages/dateparser/freshness_date_parser.py", line 46, in get_local_tz
    return get_localzone()
  File "/usr/lib/python3.6/site-packages/tzlocal/unix.py", line 131, in get_localzone
    _cache_tz = _get_localzone()
  File "/usr/lib/python3.6/site-packages/tzlocal/unix.py", line 70, in _get_localzone
    return pytz.timezone(etctz.replace(' ', '_'))
  File "/usr/lib/python3.6/site-packages/pytz/__init__.py", line 178, in timezone
    raise UnknownTimeZoneError(zone)
pytz.exceptions.UnknownTimeZoneError: ''
>>>
```

**Comment by sortafreel** [comment]
The issue feels outdated:
```
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dateparser
>>> dateparser.parse("November 5 3:30 PM")
datetime.datetime(2019, 11, 5, 15, 30)
>>>
```

**Comment by DrKendall** [comment]
It may be outdated, but still a current issue.

**Comment by sortafreel** [comment]
@DrKendall how could we reproduce it?

**Comment by DrKendall** [comment]
I don't know how I got it, but what could cause `pytz.exceptions.UnknownTimeZoneError: ''`? 
I shared it recently, does this help: https://stackoverflow.com/questions/59198852/pytz-exceptions-unknowntimezoneerror

**Comment by Gallaecio** [comment]
https://stackoverflow.com/questions/59198852/pytz-exceptions-unknowntimezoneerror suggests to me that this is not dateparser’s fault.
