### ISSUE TITLE
test suite failures in Python 3.7 and Debian unstable

### ISSUE THREAD

**Issue by anarcat** [scrapinghub/dateparser#490]
Hi!

I wonder if you could help me with a problem I'm seeing when running the test suite against the 3.7 python version in Debian buster (and unstable). this is with the 0.7.0 release but I see the same failures with the current git master branch:

```
======================================================================
FAIL: test_detection_24_es (tests.test_search.TestTranslateSearch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/parameterized/parameterized.py", line 392, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/tmp/autopkgtest.tAsRpR/build.hjW/real-tree/tests/test_search.py", line 619, in test_detection
    self.assertEqual(result, shortname)
AssertionError: 'eo' != 'es'
- eo
+ es


======================================================================
FAIL: test_search_and_parse_26_es (tests.test_search.TestTranslateSearch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/parameterized/parameterized.py", line 392, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/tmp/autopkgtest.tAsRpR/build.hjW/real-tree/dateparser/conf.py", line 81, in wrapper
    return f(*args, **kwargs)
  File "/tmp/autopkgtest.tAsRpR/build.hjW/real-tree/tests/test_search.py", line 413, in test_search_and_parse
    self.assertEqual(result, expected)
AssertionError: Lists differ: [('a', datetime.datetime(2000, 1, 1, 0, 0)),[479 chars] 0))] != [('de 1939', datetime.datetime(1939, 1, 1, 0[51 chars] 0))]

First differing element 0:
('a', datetime.datetime(2000, 1, 1, 0, 0))
('de 1939', datetime.datetime(1939, 1, 1, 0, 0))

First list contains 10 additional elements.
First extra element 2:
('a', datetime.datetime(2000, 1, 1, 0, 0))

Diff is 670 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: test_search_date_string_31_es (tests.test_search.TestTranslateSearch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/parameterized/parameterized.py", line 392, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/tmp/autopkgtest.tAsRpR/build.hjW/real-tree/tests/test_search.py", line 210, in test_search_date_string
    self.assertEqual(result, datetime_string)
AssertionError: 'M' != 'Miércoles 31 Diciembre 2014'
- M
+ Miércoles 31 Diciembre 2014

```

thanks!

**Comment by anarcat** [comment]
note that this could, of course, be related with out of sync package versions between Debian and `requirements.txt`, see #489.

**Comment by anarcat** [comment]
nevermind, I confirm this is my problem with the requirements file in #489, in that the test suite *will* fail with current versions of the dependencies...

**Comment by dotlambda** [comment]
I have the same problem in https://github.com/NixOS/nixpkgs. Please make sure the tests pass with recent versions of the dependencies!
