### ISSUE TITLE
TypeError: '<=' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by lopuhin** [scrapinghub/dateparser#621]
``dateparser.parse`` crashes when trying to parse some dates, for example:

```
>>> dateparser.parse('Oct 1 2018 4:40 PM EST —')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "dateparser/conf.py", line 82, in wrapper
    return f(*args, **kwargs)
  File "dateparser/__init__.py", line 53, in parse
    data = parser.get_date_data(date_string, date_formats)
  File "dateparser/date.py", line 417, in get_date_data
    locale, date_string, date_formats, settings=self._settings)
  File "dateparser/date.py", line 189, in parse
    return instance._parse()
  File "dateparser/date.py", line 199, in _parse
    date_obj = parser()
  File "dateparser/date.py", line 222, in _try_parser
    self._get_translated_date(), settings=self._settings)
  File "dateparser/conf.py", line 82, in wrapper
    return f(*args, **kwargs)
  File "dateparser/date_parser.py", line 26, in parse
    date_obj, period = parse(date_string, settings=settings)
  File "dateparser/parser.py", line 70, in parse
    raise exceptions.pop(-1)
  File "dateparser/parser.py", line 64, in parse
    res = parser(datestring, settings)
  File "dateparser/parser.py", line 446, in parse
    po = cls(tokens.tokenize(), settings)
  File "dateparser/parser.py", line 192, in __init__
    self.filtered_tokens = [t for t in self.tokens if t[1] <= 1]
  File "dateparser/parser.py", line 192, in <listcomp>
    self.filtered_tokens = [t for t in self.tokens if t[1] <= 1]
TypeError: '<=' not supported between instances of 'str' and 'int'
```

This is using dateparser master (2dd4c5962e16de208c6ef7a9a9f9d5efe8754eb7)

**Comment by noviluni** [comment]
It seems that the dash and the long dash weren't included in the `nowords` variable. I added a PR to fix it. Thanks for raising it, @lopuhin !

**Comment by noviluni** [comment]
Hi @lopuhin the last release includes this fix :tada:

**Comment by lopuhin** [comment]
Great, thank you so much @noviluni 👍
