### ISSUE TITLE
AttributeError in tzlocal-3.0 

### ISSUE THREAD

**Issue by skar404** [scrapinghub/dateparser#964]
I have a problem in install:

```python
dateparser==0.7.4  
tzlocal==3.0 
```

Traceback:
```python
import dateparser; dateparser.parse('2021-08-16T16:00:00').date()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "venv/lib/python3.7/site-packages/dateparser/conf.py", line 84, in wrapper
    return f(*args, **kwargs)
  File "venv/lib/python3.7/site-packages/dateparser/__init__.py", line 53, in parse
    data = parser.get_date_data(date_string, date_formats)
  File "venv/lib/python3.7/site-packages/dateparser/date.py", line 418, in get_date_data
    locale, date_string, date_formats, settings=self._settings)
  File "venv/lib/python3.7/site-packages/dateparser/date.py", line 196, in parse
    return instance._parse()
  File "venv/lib/python3.7/site-packages/dateparser/date.py", line 200, in _parse
    date_obj = self._parsers[parser_name]()
  File "venv/lib/python3.7/site-packages/dateparser/date.py", line 223, in _try_parser
    self._get_translated_date(), settings=self._settings)
  File "venv/lib/python3.7/site-packages/dateparser/conf.py", line 84, in wrapper
    return f(*args, **kwargs)
  File "venv/lib/python3.7/site-packages/dateparser/date_parser.py", line 37, in parse
    date_obj = stz.localize(date_obj)
AttributeError: 'backports.zoneinfo.ZoneInfo' object has no attribute 'localize'
```

**Comment by johntmyers** [comment]
Same for me

**Comment by johntmyers** [comment]
@skar404 changing to `tzlocal==2.1.0` is a temporary fix that works for me

**Comment by skar404** [comment]
@johntmyers thanks, 

maybe create fix in old version and push to pypi?

**Comment by johntmyers** [comment]
I do think that dependency should have been pinned to a degree, but any changes to these deps should probably be looked at by the owners.

**Comment by CarolynWebster** [comment]
This error popped up for me when I updated `pytz` to `2021.1` from `2020.1`

**Comment by CarolynWebster** [comment]
Upgrading to `dateparser==1.0.0` worked to resolve my issue. We are not using `tzlocal`

**Comment by noviluni** [comment]
Hi, thank you for reporting this. This is something that was reported in the past and fixed here: https://github.com/scrapinghub/dateparser/pull/792.

Is not possible to use `dateparser` <= 1.0.0 with `tzlocal>=3.0`. 

As some of you mentioned, to fix the issue you can either upgrade to the new dateparser version (that includes a lot of improvements vs the older versions, but doesn't support Python <= 3.5) or pin tzlocal<=3.0.


> maybe create fix in old version and push to pypi?

I'm not sure what do you mean, but we don't release fixed for old versions. To get the fixes you need to update to newer versions.

I will close the issue. Please, feel free to comment here again or open new issues in case there's something you think is not correct :)

Thanks again!
